### ISSUE TITLE
Set a more specific tax name so the Taxes report is less ambiguous

### ISSUE THREAD

**Issue by DanReyLop** [taxjar/taxjar-woocommerce-plugin#109]
Issue reported in WooCommerce Services: https://github.com/Automattic/woocommerce-services/issues/1620

For an order with auto-calculated taxes, TaxJar gives a name to the tax rate using [this logic](https://github.com/taxjar/taxjar-woocommerce-plugin/blob/master/includes/class-wc-taxjar-integration.php#L454). So, for example, when a customer from Dallas, TX buys an item, the order has a tax rate called `TX Tax`.

On the `WooCommerce -> Reports -> Taxes` table (`http://[YOUR-SITE]/wp-admin/admin.php?page=wc-reports&tab=taxes`), that tax rate will have this code: `US-TX-TX TAX-1`. Even if the site gets orders from different customers from differents parts of Texas, all the different tax rates will have the same `US-TX-TX TAX-1` name. That makes reporting quite confusing.

The `Reports -> Taxes` table uses this logic to set a tax name ([see here](https://github.com/woocommerce/woocommerce/blob/d5ab20d1a5cc7feccc28892724a8b642e8cf8c1c/includes/class-wc-tax.php#L696)): `[COUNTRY]-[STATE]-[TAX_NAME]-[PRIORITY]`. The "tax name" produced by TaxJar should have a more specific name, for example `Dallas Tax`. In that case, the report would read `US-TX-DALLAS TAX-1`, which is less ambiguous.

**Comment by dallendalton** [comment]
Thanks for reporting this issue. We have added it to our road map and will add any updates to this thread as they become available.

**Comment by kellyphillipsnc** [comment]
Hello. It looks like this issue has not been updated for the past 10 months. It's an issue for everyone who pays sales tax in the state of NC and I'm sure other county-based states. Is there a timeline for this issue to be resolved? Thank you!

**Comment by dougm1966** [comment]
Has this been updated? It's the same for Oklahoma as well. Although in Oklahoma there is a county, city and state sales. Still can't wrap my head around that as there isn't a place in Woocommerce for a 3rd tax. Would love some feedback on this if someone knows a solution.

**Comment by dallendalton** [comment]
Hi @dougm1966,

So unfortunately, out of the box WooCommerce only uses four values in their tax table (country, state, city and zip). While this can suffice for some areas it is not granular enough for many jurisdictions. There are areas that have multiple sales tax rates within a given city and zip code. There are also jurisdictions where the tax rate is dynamic based off other details of the order (order total, products in the cart, etc).

TaxJar is built to handle all these scenarios. Regardless of what is in the WooCommerce tax table, the TaxJar plugin sends all the necessary cart data to TaxJar to do an accurate sales tax calculation for each unique cart. We only create rates in the WooCommerce tax table as a way to interface with the WooCommerce API.

Regarding reporting, we have reprioritized the fix to make the rates a little more granular as originally requested in this issue. However you should be aware that even with that change those rates will change dynamically based on the last cart that tax was calculated on in that area. Also in many jurisdictions there is not enough information in that report to accurately file. We recommend that you use the Sales Tax Reports within the TaxJar app for more detailed and accurate tax reports.

**Comment by dougm1966** [comment]
@dallendalton Thank for the clear explanation. Still looking into the best option when it comes to automated taxes for Woocommerce.

**Comment by dallendalton** [comment]
I am closing this issue due to its age to help clean up the repository. We have recorded this feature request, however, it is not currently on the roadmap. Thanks again for submitting this suggestion.
