### ISSUE TITLE
Dynamic tax category filter

### ISSUE THREAD

**Issue by ryan-boder** [taxjar/taxjar-woocommerce-plugin#110]
My company sells a service that TaxJar does not yet have a tax a [tax category](https://developers.taxjar.com/api/reference/#get-list-tax-categories) for. As a workaround we set the product's tax class as "General Services - 19000" and added a few lines to get_line_items() in class-wc-taxjar-integration.php so that in some states TaxJar will treat the product as fully taxable instead of general services. This simulates the tax behavior of our service.

```
// In function get_line_items ...
	if ( isset( $tax_class ) && is_numeric( end( $tax_class ) ) ) {
		$tax_code = end( $tax_class );

		//// Treat general services as regular product in some states
		if ($tax_code === '19000') {
			$address = $this->get_address($wc_cart_object);
			if ($address['to_state'] && in_array($address['to_state'], ['AL', 'AK', 'AZ', 'AR'])) {
				$tax_code = '';
			}
		}
		//////////////////////////////////////////////////////////////////////////////////////////////
	}
```

Would you be willing to add a filter to the plugin so that we can move this code out of the taxjar plugin and put it cleanly in an other plugin or in functions.php? I imagine others might be in a similar situation where the categories taxjar provides aren't sufficient and they need to implement some kind of dynamic tax code logic.

Something like this might work...

```
add_filter('taxjar_get_line_items', function($line_items, $wc_cart_object){
	// Manipulate tax code for each line item
	return $line_items;
});
```

**Comment by ryan-boder** [comment]
Requested PR https://github.com/taxjar/taxjar-woocommerce-plugin/pull/111

**Comment by dallendalton** [comment]
Closed, see comment in https://github.com/taxjar/taxjar-woocommerce-plugin/pull/111 for details of implementation.
