### ISSUE TITLE
Exempt Customers

### ISSUE THREAD

**Issue by bhubbard** [taxjar/taxjar-woocommerce-plugin#114]
Hey Everyone,

I can see thru the API Documentation that we can manage [Exempt Customers](https://developers.taxjar.com/api/reference/#customers). 

Do plans exist to implement this into the Woo plugin? If so how? Can we help? As this is a feature we need for our use case.

**Comment by douglsmith** [comment]
SmartCalcs does check for exempt customers at the time of the sale. You can see that in /includes/class-wc-taxjar-integration.php on lines [315](https://github.com/taxjar/taxjar-woocommerce-plugin/blob/c3ae6752573dd0c9eafd39540b88ce8fcb9eb9f7/includes/class-wc-taxjar-integration.php#L315) and [397](https://github.com/taxjar/taxjar-woocommerce-plugin/blob/c3ae6752573dd0c9eafd39540b88ce8fcb9eb9f7/includes/class-wc-taxjar-integration.php#L397).

But I don't know if this is considered when the orders are pulled into TaxJar. We asked support a while back but couldn't get a confident answer either way. We also haven't done enough testing yet to know that way.

**Comment by dallendalton** [comment]
@bhubbard and @douglsmith - Hopefully I can help shed some light on what's currently supported in the plugin and what is on the road map. 

@douglsmith - You are correct in that the plugin currently honors the "VAT exempt" setting that can be added to a customer. When a customer is VAT exempt the plugin basically skips the calculations for that order and no taxes are applied to it. However, this setting is not currently supported when orders are pulled into TaxJar. In the TaxJar app these orders will show as having zero tax collected but will also show that an amount that was "expected" to be collected. This will cause discrepancies between the expected and collected reports.

Development has already started on building in support for customer exemptions into the plugin. We have a major new version coming out next month that changes how we get orders from WooCommerce stores into TaxJar (currently we pull them in through the WooCommerce API but this new version will switch to a near real time push from the store into TaxJar through the TaxJar API). This is a necessary first step in fully supporting customer exemptions.

Shortly after that version launches there will be another update containing support for customer exemptions. This will allow you to classify customers based on their exemption type and exemption regions for correct tax calculation on orders and in the reporting and filing inside of the TaxJar app. I expect this version to be release around the end of August.

**Comment by mjmarley** [comment]
Thanks @dallendalton for rolling out these changes. They are very important for our business.

**Comment by dallendalton** [comment]
The support for customer exemptions inside of the TaxJar plugin is available in today's release, https://github.com/taxjar/taxjar-woocommerce-plugin/releases/tag/3.0.4. To set a customer exemption you can simply go into the edit customer page in the dashboard and select their exemption type and exempt states from the drop downs in the TaxJar Sales Tax Exemptions section. This will automatically sync the customer to TaxJar and apply the exemption to any future orders that they place.
