### ISSUE TITLE
Save Exempt Reason to Order

### ISSUE THREAD

**Issue by bhubbard** [taxjar/taxjar-woocommerce-plugin#127]
It would be great if a customer is exempt, that we save the reason to the order as metadata. This way if the customer exemption changes later, we can still see why the tax was $0 at the time of the order.

**Comment by dallendalton** [comment]
Hi @bhubbard, I think this is a great idea and something that we can add to our plugin in the future. Thanks!

**Comment by dallendalton** [comment]
I am closing this issue due to its age to help clean up the repository. We have recorded this feature request, however, it is not currently on the roadmap. Thanks again for submitting this suggestion.
