### ISSUE TITLE
Temporary ignore Exemptions

### ISSUE THREAD

**Issue by bhubbard** [taxjar/taxjar-woocommerce-plugin#129]
Our company is primarily B2B, and many of our clients are resellers. However sometimes clients will order products as NFR (Not For Resale) in which case we need to charge taxes even if we have them marked as exempt for the state they are shipping too. 

How can we temporarily ignore an exemption for a user during checkout and charge tax for a single order?

**Comment by dallendalton** [comment]
@bhubbard , if an order level exemption is set for the order, it will override the customer level exemption. You can see the order level exemption parameter in our documentation here: https://developers.taxjar.com/api/reference/#post-create-an-order-transaction

It has the name "exemption_type". You can set this parameter using these filters:
taxjar_order_sync_exemption_type
taxjar_refund_sync_exemption_type

By default it is set to an empty string, but setting it to "non_exempt" will cause the order to be taxed regardless of the customer exemption status. Using those filters will allow you to handle the scenario you mentioned.
