### ISSUE TITLE
Feature Request - Webhooks

### ISSUE THREAD

**Issue by bhubbard** [taxjar/taxjar-woocommerce-plugin#135]
So I know this may not be the best place, but we would love to see taxjar offer webhooks. On the WordPress site, maybe just hooking into WooCommerce webhooks feature to show what options are best available, such as syncing a customer, etc. But we would really like to see webhooks via the native TaxJar experience, not specific to WordPress.

**Comment by dallendalton** [comment]
@bhubbard - Thanks for the feedback! Could you elaborate a little more on what your use case would be for these webhooks? I want to gather as much information as possible to see if this is something we want to prioritize in the future. Thanks!

**Comment by bhubbard** [comment]
Sure, so when a customer or transaction (order) gets added/updated/deleted from TaxJar trigger a TaxJar webhook. This could be used for syncing operations with other systems, or say send an email/slack/pubsub/etc message to people/systems who want to be notified of any changes. 

For our use case, we would probably setup slack notifications for our billing/accounting team. We would also probably trigger a Google Cloud Function to verify the customer data matches what we have for the custom system we built to manage Tax Resell Certificates.

**Comment by dallendalton** [comment]
I am closing this issue due to its age to help clean up the repository. We have recorded this feature request, however, it is not currently on the roadmap. Thanks again for submitting this suggestion.
