### ISSUE TITLE
Taxes for the Canary Islands

### ISSUE THREAD

**Issue by Meganitrospeed** [taxjar/taxjar-woocommerce-plugin#138]
Its calculating the taxes for the Canary Islands ( which are part of Spain ) as if it was Spain ( 21% )
The Canary Islands is a "Special Tax Region" where the tax applied is called IGIC and is only 7%

**Comment by dallendalton** [comment]
@Meganitrospeed - Sorry for the delay in getting back to you on this. Currently we do not support the IGIC tax. 

Also for faster response times to issues like this feel free to contact us directly through our support by emailing us at support@taxjar.com. Thanks!
