### ISSUE TITLE
Dev/Staging Sites - Disable Sync

### ISSUE THREAD

**Issue by bhubbard** [taxjar/taxjar-woocommerce-plugin#140]
@dallendalton 

So for our site we have been noticing some issues with syncing exemptions to TaxJar. One thing I would like to rule out is local dev and staging servers syncing. What is the best way to disable sync now on these installs?

Can we have a setting in the plugin to set the site as dev/staging and disable the user exemption syncing?

**Comment by dallendalton** [comment]
So currently the best way would be to add a filter to your staging site.

```
add_filter( 'taxjar_should_sync_customer', 'staging_taxjar_no_sync' );

function staging_taxjar_no_sync( $should_sync ) {
    return false;
}
```
I do think having a setting for a staging site would be very helpful. I'll bring this to the attention of the team and respond here once we have decided when/if to prioritize adding this. Thanks for your feedback and helping us to make our plugin better!

**Comment by devinsays** [comment]
Just want to verify this approach should also work fine @dallendalton?

```php
/**
 * Allow 'Sales Tax Reporting' only on production.
 *
 * @param $option
 *
 * @return array
 */
function prefix_staging_disable_taxjar_sync( $option ) {

    // Logic for identifying your production site.
    // https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/
	if ( 'production' === wp_get_environment_type() ) {
		return $option;
	}

	if ( ! is_array( $option ) ) {
		return $option;
	}

	if ( isset( $option['taxjar_download'] ) ) {
		$option['taxjar_download'] = 'no';
	}

	return $option;
}
add_filter( 'option_woocommerce_taxjar-integration_settings', 'prefix_staging_disable_taxjar_sync' );
```

**Comment by dallendalton** [comment]
@devinsays - I haven't actually tested the snippet your provided but it looks like it should work correctly. However this snippet would only prevent orders and refunds from syncing to TaxJar. For customers, you would also have to disable the tax calculation setting as well. (Customers are tied in with the tax calculation setting since they are necessary to the calculation process when the have been exempted in WooCommerce).

`$option[ 'api_calcs_enabled' ] = 'no';`

**Comment by davelozier** [comment]
We just noticed this issue as well. For the time being our solution is to prevent the plugin from being loaded in non production environments.

I wouldn't consider this as an enhancement but rather a bug. We're use simulated transactions in our dev/staging environments for testing.  Allowing these transactions to affect production data is a real issue..

**Comment by davelozier** [comment]
This is the code we're using in a MU plugin to prevent TaxJar from being loaded in non production environments. Maybe someone else will find it useful.
```
add_filter( 'option_active_plugins', function( $plugins ) {
    if ( 'production' !== wp_get_environment_type() ) {
        return array_diff( $plugins, ['taxjar-simplified-taxes-for-woocommerce/taxjar-woocommerce.php'] );
    }
    return $plugins;
});
```

**Comment by dallendalton** [comment]
@davelozier Thanks for adding additional context to this issue. We are currently investigating how we should best handle this scenario. While preventing staging/development data from getting into production TaxJar accounts is very important, we also have customers who test out TaxJar using a trial account and want to test the end to end process. We are looking into how we can support both these cases and will update this card when we have more info.

**Comment by dallendalton** [comment]
I am closing this issue due to its age to help clean up the repository. We have recorded this feature request, however, it is not currently on the roadmap. Thanks again for submitting this suggestion.
