### ISSUE TITLE
Exempt Customers API

### ISSUE THREAD

**Issue by bhubbard** [taxjar/taxjar-woocommerce-plugin#141]
It would be useful if the TaxJar api showed a timestamp for one an exempt customer was created or last modified. 

I also notice in the UI you can upload a cert file, any plans to have that added to the api as well?

**Comment by dallendalton** [comment]
Hey @bhubbard, I will forward the first request on to our product team. Regarding the uploading the cert through the API, this is something that has been discussed but is not on our immediate roadmap at this time. Thanks!
