### ISSUE TITLE
Support for WordPress Rest API

### ISSUE THREAD

**Issue by bhubbard** [taxjar/taxjar-woocommerce-plugin#142]
I would love to see support for WordPress Rest API:

* Sync all users to Taxjar
* Sync individual user to Taxjar
* Sync Transactions
...

**Comment by dallendalton** [comment]
Hey @bhubbard, thanks for your feedback! I can see how this would be beneficial and I'll add the request to our internal list so we can discuss it. When/if we decide to add this to the plugin I'll post an update here. Thanks again!
