### ISSUE TITLE
Notice on Settings Page for connected_email

### ISSUE THREAD

**Issue by bhubbard** [taxjar/taxjar-woocommerce-plugin#157]
Notice: Undefined index: connected_email in /Users/bhubbardnew/Local Sites/access-new/app/public/wp-content/plugins/taxjar-woocommerce-plugin/includes/class-wc-taxjar-integration.php on line 1412

https://share.getcloudapp.com/o0ug0x2L

**Comment by dallendalton** [comment]
@bhubbard - Thanks for reporting this issue! We are taking a look and will post an update here as soon as one is available.

**Comment by dallendalton** [comment]
@bhubbard - We've replicated and identified the issue and should have a fix included in our next release. Thanks again for reporting this!

**Comment by sethobey** [comment]
Resolved with #152
