### ISSUE TITLE
Order total on cart page doesn't include shipping taxes

### ISSUE THREAD

**Issue by tonkapark** [taxjar/taxjar-woocommerce-plugin#16]
When using a flat rate shipping option and putting items in a cart on WooCommerce, after calculating shipping the taxes are calculated and properly displayed as tax on the item and shipping but the order total is only the items + shipping + item tax. The shipping tax is not included for some reason.

I think the solution is to add this line after 528 in class-wc-taxjar-integration.php

`$wc_cart_object->shipping_tax_total = $this->shipping_collectable;`

**Comment by 0x5378** [comment]
Issue has been fixed in last update.
