### ISSUE TITLE
Version of action-scheduler?

### ISSUE THREAD

**Issue by n9yty** [taxjar/taxjar-woocommerce-plugin#162]
We are having an issue on our site where webhooks on subscription updates are sometimes getting the wrong status. WooCommerce support asked us to search the plugin code to look for anything adjusting the number of concurrent batches in action scheduler.

They saw the library/action-scheduler in the taxjar plugin and pointed out that it had a defualt of 5 concurrent batches as opposed to 1 in the official action-scheduler.

What version of action-scheduler is TaxJar using in the plugin? Is the code in the library only used if the system doesn't have action-scheduler running, or is it using the code all the time? If so, can the number of concurrent batches be updated to match the current action-scheduler, or maybe better, can the included version be updated to the lastest v3.1.6 instead of 2.2.5 that is in there, or would that cause other issues?

**Comment by dallendalton** [comment]
Hi @n9yty,

Thanks for your question. We do include action scheduler in our plugin. However the way action scheduler is built, it actually ensures that the most recent version of the library is used. So for example if TaxJar includes version 2.2.5 and WooCommerce includes version 3.1.6, WordPress will only use the most recent of the two (in this case 3.1.6). You can get more information on this on action schedulers site in the [Loading Action Scheduler section](https://actionscheduler.org/usage/).

**Comment by n9yty** [comment]
I assumed as much, but they (support) seem convinced that somehow your plugin is responsible for changing the number of concurrent batches. I don't believe they have even confirmed that number has, in fact, been changed, but by the code scan they saw the value in there and are saying it is not their issue. :(

**Comment by dallendalton** [comment]
Closing this issue as it is no longer relevant to recent versions of the TaxJar plugin. Action Scheduler is not longer directly included in the plugin as all supported versions of WooCommerce include it.
