### ISSUE TITLE
TaxJar removes international tax rates on plugin activation

### ISSUE THREAD

**Issue by devinsays** [taxjar/taxjar-woocommerce-plugin#177]
We are using TaxJar for domestic (US) tax rates, and filing our Australia (AU) and United Kingdom (GB) tax rates separately.

One issue we encountered is that this plugin appears to have truncated the entire tax rates table on activation (https://github.com/taxjar/taxjar-woocommerce-plugin/blob/master/taxjar-woocommerce.php#L269) which wiped out our international tax rates.

We didn't realize the rates were missing for a couple days, which led to some loss of revenue from AU and GB and required manual fixes for the orders.

Ideally, I think there should be a notice before deleting site data- especially with non-domestic tax rates.

**Comment by dallendalton** [comment]
@devinsays, Thanks for submitting this issue. We are currently working on a fix that will improve the user experience and functionality around the clearing of the tax rates. I'll provide an update here as the fix is available.

**Comment by dallendalton** [comment]
@devinsays - We have decided to include this work as part of a larger project we have ongoing (around making the tax calculations more efficient and adding backup rates to the plugin). So while this is still included in our roadmap, it may be a couple of months before it is actually released. Thanks!

**Comment by dallendalton** [comment]
I am closing this issue due to its age to help clean up the repository. This feature did not end up being part of the work previously scoped. We still have this request recorded. However, it is not currently on the roadmap. Thanks again for submitting this suggestion.

**Comment by devinsays** [comment]
@dallendalton I urge you to reconsider. This is a serious issue with the plugin. Existing tax rates should not be flushed without notice.

In our case, all our subscriptions renew on the 1st, and this caused us to miss ~$5k in tax charges for our international customers after this plugin had been activated.

**Comment by dallendalton** [comment]
@devinsays Thanks for the additional comment and context. I will resurface this internally and will update this thread once we have made a decision.
