### ISSUE TITLE
Subscription renewal doubles line item tax

### ISSUE THREAD

**Issue by pogla** [taxjar/taxjar-woocommerce-plugin#178]
## Steps to reproduce

1. Update the plugins to the latest versions. It also doesn't work with older versions.

<img width="1423" alt="Screenshot 2021-02-11 at 17 57 17" src="https://user-images.githubusercontent.com/6359466/107670224-cd47ec80-6c92-11eb-983f-094eb5ff1ac2.png">

2. Create a subscription. Use a delivery address that pulls tax rate via the TaxJar API. We are using a tax class on the product but I don't think it matters.
3. Process renewal

<img width="1819" alt="Screenshot 2021-02-11 at 18 00 45" src="https://user-images.githubusercontent.com/6359466/107670536-1f890d80-6c93-11eb-85da-578d2056435b.png">

4. Line item gets double taxes applied.

<img width="1819" alt="Screenshot 2021-02-11 at 18 01 30" src="https://user-images.githubusercontent.com/6359466/107670668-42b3bd00-6c93-11eb-9425-cd0058fb180e.png">

5. If you press `Recalculate`, it gets recalculated properly.

-------

I traced down the issue to [this loop](https://github.com/taxjar/taxjar-woocommerce-plugin/blob/master/includes/class-wc-taxjar-integration.php#L1118-L1129). So the loop will add a tax line item for each existing line item. Even if the tax item already exists.

**Comment by dallendalton** [comment]
This is resolved with the fix in #179
