### ISSUE TITLE
Fee lines prevent TaxJar sync

### ISSUE THREAD

**Issue by devinsays** [taxjar/taxjar-woocommerce-plugin#183]
We noticed some order of our orders are not syncing into TaxJar even though the order had taxes charged.

The scheduled action failed with this notice:

```
Invalid request sent to TaxJar. Details: Order amount must be equal to the sum of line items and shipping
```

It appears the pattern with all these items is that they have fee lines.

Here's an example order with the results from the woocommerce_order_items table:

| order_item_id | order_item_name     | order_item_type | order_id |
|---------|--------------------|-----------|---------|
| 8963740 | Yum Yum Box        | line_item | 6360409 |
| 8963741 | Expedite First Box | fee       | 6360409 |
| 8963742 | Referral Discount  | fee       | 6360409 |
| 8963743 | Free               | shipping  | 6360409 |
| 8963744 | US-OK-OK TAX-1     | tax       | 6360409 |

The referral fee specifically looks like this:

| meta_id  | order_item_id | meta_key       | meta_value                                      |
|----------|---------------|----------------|-------------------------------------------------|
| 72843667 | 8963742       | _fee_amount    | -5                                              |
| 72843668 | 8963742       | _tax_class     | 0                                               |
| 72843669 | 8963742       | _tax_status    | taxable                                         |
| 72843670 | 8963742       | _line_total    | -5                                              |
| 72843671 | 8963742       | _line_tax      | -0.46                                           |
| 72843672 | 8963742       | _line_tax_data | a:1:{s:5:"total";a:1:{i:6794;s:9:"-0.458036";}} |

I am wondering what the best solution for this is. Does this integration not work with fee lines? Or are we doing something specific that is breaking the integration?

**Comment by dallendalton** [comment]
@devinsays Thanks for submitting this issue. The TaxJar plugin is fully compatible with the use of fee lines. However, in this case a negative fee has been added to the order. In effect this fee is acting as a discount. We do not currently support this use case.

We are looking into if we can and should add support for this use case and will update this issue when we have more information.

Thanks!

**Comment by devinsays** [comment]
Hi @dallendalton. We were using negative fee lines to apply a referral credit to new orders. However, we were able to rewrite this functionality to apply a referral coupon instead. I think this makes more sense anyways from an accounting/finance perspective and also resolves the issue we were seeing with TaxJar. So support for this use case is no longer needed on our side. However, I think it would be useful to surface a notice or trigger an admin email if TaxJar encounters this condition and does not plan to support it.

**Comment by dallendalton** [comment]
@devinsays - I'm glad you were able to get this figure out. I agree that we need a greater ability to surface issues when syncing transactions to TaxJar. It's something that we have on our roadmap as part of pretty major upcoming improvements. Thanks again for bringing this issue up!
