### ISSUE TITLE
Allow for sending requests to https://api.sandbox.taxjar.com

### ISSUE THREAD

**Issue by boblinthorst** [taxjar/taxjar-woocommerce-plugin#184]
Reading through https://developers.taxjar.com/integrations/testing/. If you want to test taxJar using their staging environment. You want to point your API client, to the sandbox URL ( `https://api.sandbox.taxjar.com` ). 

Unfortunately, this plugin does not have a setting to point it to the sandbox. Nor is the place where the URL is set, filterable.

**Comment by dallendalton** [comment]
@boblinthorst - Thanks for submitting this issue! We agree that having the URL filterable is the best approach here and will add a filter to the plugin in the next couple of weeks. Before using the sandbox, please make sure to you are aware of any limitations of the sandbox which can be found [in our API documentation](https://developers.taxjar.com/api/reference/#sandbox-environment).

**Comment by dallendalton** [comment]
I am closing this issue due to its age to help clean up the repository. We have recorded this feature request. However, it is not currently on the roadmap. Thanks again for submitting this suggestion.
