### ISSUE TITLE
Fatal error when store processes subscription renewal

### ISSUE THREAD

**Issue by alexrlangford** [taxjar/taxjar-woocommerce-plugin#193]
I am encountering a fatal error in this plugin when a subscription renewal order is processed. The error in question appears to be the same as in issue #192, though the circumstances surrounding it are different.

One of the store's automatic subscription renewals failed, generating a notice in WordPress. When I tried to follow the documentation steps (https://docs.woocommerce.com/document/subscriptions/scheduled-action-errors/) and manually renew the subscription, I received the following PHP error:

> Fatal error: Uncaught Error: Call to a member function get_tax_rate() on bool in /nas/content/live/tkmgacademy/wp-content/plugins/taxjar-simplified-taxes-for-woocommerce/includes/TaxCalculation/class-order-tax-applicator.php:151 Stack trace: #0 /nas/content/live/tkmgacademy/wp-content/plugins/taxjar-simplified-taxes-for-woocommerce/includes/TaxCalculation/class-order-tax-applicator.php(111): TaxJar\Order_Tax_Applicator->get_product_line_item_tax_rate(3569, Object(WC_Order_Item_Product)) #1 /nas/content/live/tkmgacademy/wp-content/plugins/taxjar-simplified-taxes-for-woocommerce/includes/TaxCalculation/class-order-tax-applicator.php(93): TaxJar\Order_Tax_Applicator->create_product_tax_rate(3569, Object(WC_Order_Item_Product)) #2 /nas/content/live/tkmgacademy/wp-content/plugins/taxjar-simplified-taxes-for-woocommerce/includes/TaxCalculation/class-order-tax-applicator.php(82): TaxJar\Order_Tax_Applicator->create_rate_and_apply_to_product_line_item(3569, Object(WC_Order_Item_Product)) #3 /nas/content/live/tkmgacademy/wp-conten in /nas/content/live/tkmgacademy/wp-content/plugins/taxjar-simplified-taxes-for-woocommerce/includes/TaxCalculation/class-order-tax-applicator.php on line 151

The only line item in this order is a variable subscription product, with no sales tax collected on it.

Some additional background is that this store was switched from AvaTax to TaxJar earlier this month. I tested on a staging site to see if this switch might be a cause of this issue and was not able to recreate it so it appears to be something else.

Plugin versions:

WordPress: 5.7.2
WooCommerce: 5.4.2
TaxJar: 3.2.10

Let me know if there's any other info I can provide to help resolve this issue.

**Comment by dallendalton** [comment]
@alexrlangford Thanks for submitting this issue. We are currently investigating it (along with https://github.com/taxjar/taxjar-woocommerce-plugin/issues/192) and will post an update here as soon as we have more information.

Is this error occurring when any subscription renewal is processed on your site or are there renewals that are going through correctly as well?

**Comment by dallendalton** [comment]
Thanks for the additional information, we are working on getting a fix out for this as soon as possible. In the meantime you may want to roll back to an older version of our plugin if you are still using the effected version on your production site.

**Comment by dallendalton** [comment]
This issue is fixed on https://github.com/taxjar/taxjar-woocommerce-plugin/pull/194 which has now been released.
