### ISSUE TITLE
No tax calculated in checkout

### ISSUE THREAD

**Issue by smarie33** [taxjar/taxjar-woocommerce-plugin#20]
If the user does not calculate shipping on the cart page and goes to checkout, no tax is ever calculated. Even after filling out the billing area. Suggest javascript that checks country/state/zip when any of those fields change and ajax to change tax area.

**Comment by fastdivision** [comment]
@smarie33 This might be a theme issue. Have you tested our plugin with a different theme such as Storefront? Can you send an email to support@taxjar.com with more information about your store so we can take a closer look? Thank you!

**Comment by smarie33** [comment]
Turns out the issue was the plugin WooCommerce Checkout Manager (which allows me to make fields required and add new ones) :-/ Thank you for your time!
