### ISSUE TITLE
is_ajax() is deprecated: Use wp_doing_ajax() instead

### ISSUE THREAD

**Issue by n9yty** [taxjar/taxjar-woocommerce-plugin#212]
Messages logged when debugging is turned on:

>> The is_ajax function is deprecated since version 6.1.0. Replace with wp_doing_ajax.

This is self-explanatory, but a reference is here:

https://github.com/Automattic/jetpack/issues/22350

The call is being made here:

./taxjar-simplified-taxes-for-woocommerce/includes/class-taxjar-tax-calculation.php:135:		return is_cart() && is_ajax();

We have a lot of installed plugins that are also making this call, so I can not verify it is your plugin that is creating the log entries, but I am pointing it out for examination purposes.

**Comment by dallendalton** [comment]
@n9yty Thanks for submitting this. We have a release that is about ready to go out that will include this fix in our plugin. Thanks again!
