### ISSUE TITLE
Ignores discount from WooCommerce PDF Product Vouchers

### ISSUE THREAD

**Issue by rlunden** [taxjar/taxjar-woocommerce-plugin#228]
When TaxJar calculates its taxes it ignores the discount when applying a coupon created with the WooCommerce PDF Product Vouchers plugin so the total is unchanged as if the coupon never was applied.
![image](https://user-images.githubusercontent.com/7823044/168237666-fbcc1839-d987-4617-87c5-5dbbb9c0c405.png)

**Comment by dallendalton** [comment]
Thanks for submitting this issue. We are currently investigating it and will post an update once we have one.

**Comment by rlunden** [comment]
Thanks @dallendalton. Any progress?

**Comment by dallendalton** [comment]
@rlunden Thanks for your patience on this. We now have a branch up for testing a fix for this issue: 

https://github.com/taxjar/taxjar-woocommerce-plugin/tree/product-pdf-voucher-support

Could you confirm this resolves the issue?

Thanks!

**Comment by rlunden** [comment]
@dallendalton It resolves the scenario when you have tax, but instead now it doesn't work when there is no tax:
![image](https://user-images.githubusercontent.com/7823044/173780751-d213a3b3-35f4-4927-b13f-40e97aba5b7f.png)

**Comment by dallendalton** [comment]
Thanks for testing this! We are working on an update to the fix to resolve this and will hopefully have it up for testing tomorrow.

**Comment by dallen-stripe** [comment]
We have updated that branch and it fixes this if you would like to test again. Thanks!

**Comment by dallendalton** [comment]
We have updated that branch and it fixes this if you would like to test again. Thanks!

**Comment by dallendalton** [comment]
This issue has been resolved in the latest release. Thanks again!
