### ISSUE TITLE
HPOS Release?

### ISSUE THREAD

**Issue by a432511** [taxjar/taxjar-woocommerce-plugin#250]
I saw that HPOS support was merged. Is there timing on the next release where this will be incorporated? This is the last plugin on my list to get HPOS running on a few sites. Thanks!

**Comment by ForestParks** [comment]
Waiting on this too, as a bunch of people are.

**Comment by smolentzov-stripe** [comment]
Hi @a432511 and @ForestParks - a new version of the plugin has been released that includes HPOS support. Thank you!

**Comment by a432511** [comment]
Thank you!
