### ISSUE TITLE
Calculate tax on WooCommerce Subscription renewals

### ISSUE THREAD

**Issue by fastdivision** [taxjar/taxjar-woocommerce-plugin#37]
Currently we calculate sales tax on the initial subscription, but not during the renewal process. We should be able to handle this with the `woocommerce_scheduled_subscription_payment` event. Out of the box, WooCommerce Subscriptions recommends [doing this manually](https://docs.woocommerce.com/document/subscriptions/renewal-process/#section-2).

Related: https://wordpress.org/support/topic/woocommerce-subscription-8/
Action hooks: https://docs.woocommerce.com/document/subscriptions/develop/action-reference/

**Comment by ryan-boder** [comment]
Hi, what is the status on this enhancement? Is it still going to happen? It was opened a year and a half ago and I need it for my company's services. It looks like [AvaTax has had this feature for 2 years](https://www.skyverge.com/blog/sell-subscriptions-woocommerce-get-sales-tax-right/).

**Comment by dallendalton** [comment]
@ryan-boder This is currently in development, and should be released within about a month. Thanks!

**Comment by ryan-boder** [comment]
Awesome thanks!

**Comment by fastdivision** [comment]
We did it! Merged and resolved in #107
