### ISSUE TITLE
Subscription sign-up fees are not being accounted for, making taxes incorrect

### ISSUE THREAD

**Issue by jeffstieler** [taxjar/taxjar-woocommerce-plugin#45]
This issue was first created in the WCS repo: https://github.com/Automattic/woocommerce-services/issues/1250

I've tested with WCS disabled and only TaxJar in play - the bug still occurs. It seems that somehow with TaxJar calculations enabled, the sign up fee is completely dropped from the line items. Not only is the tax incorrect, the sign up fee won't be collected.

Quoting @NickGreen from https://github.com/Automattic/woocommerce-services/issues/1250:

> Internal Prospress ticket #2710
> 
> ### Problem
> 
> The Signup Fee is not being accounted for in the total making taxes incorrect. This is being reported on several tickets.
> 
> ### Duplication
> 
> WooCommerce Services: by Automattic - 1.9.0
> WooCommerce Subscriptions: by Prospress Inc. - 2.2.15
> WooCommerce: by Automattic - 3.2.5
> 
> Set up subscription product for a 16.99/month with 1 month free and a $600 dollar signup fee.
> 
> Cart totals
> 
> SUBTOTAL $16.99
> TAX $1.32
> TOTAL $18.31
> RECURRING TOTALS
> SUBTOTAL $16.99 / month
> TAX $1.32 / month
> RECURRING TOTAL $18.31 / month
> First renewal: December 22, 2017
> 
> Confirmed that each product is marked as taxable with the standard rate.

**Comment by fastdivision** [comment]
@jeffstieler Thanks for opening this issue! I'm halfway there with a fix, still trying to devise a solution to pass the sign-up fee to our API for tax calculations. Related PR: https://github.com/taxjar/taxjar-woocommerce-plugin/pull/47

**Comment by fastdivision** [comment]
@jeffstieler Got this working, will deploy after a review from the team.

**Comment by beast3500** [comment]
I had a similar issue where there is interference caused when I have Woocommerce/Woocommerce Services and jetpack enabled at the same time. Basically it completely screws up my tax calculations not to mention it makes each of my products that are subscription based (with a 600,800, 1000 dollar sign up fee) cost a total of 16 dollars total . As soon as I disable jetpack, everything is back to normal but I get no tax calculations. Really hoping for a solution soon!

**Comment by fastdivision** [comment]
@beast3500 I'm sorry about the inconvenience this is causing. Once we get this merged into the TaxJar plugin (hopefully this week), I'm certain it will be ported over to WooCommerce Services shortly.

**Comment by fastdivision** [comment]
@jeffstieler Merged #47 for release in the TaxJar plugin shortly. Let's get it into WCS! /cc @beast3500

**Comment by beast3500** [comment]
Any idea of the timeline here?

**Comment by fastdivision** [comment]
@beast3500 See https://github.com/Automattic/woocommerce-services/pull/1265
