### ISSUE TITLE
Taxes not calculated properly for British Columbia, Manitoba, and Saskatchewan

### ISSUE THREAD

**Issue by jeffstieler** [taxjar/taxjar-woocommerce-plugin#49]
From https://github.com/Automattic/woocommerce-services/issues/1253 (cc: @mikeyarce)

Canada Post only requires GST when shipping things from British Columbia, Manitoba, and Saskatchewan.  

From Canada Post:
https://www.canadapost.ca/web/en/kb/details.page?article=collecting_sales_tax&cattype=kb&cat=generalinquiries&subcat=generalinformation

Here's how the taxes are split up for these provinces:
![screen shot 2017-12-01 at 14 37 14](https://user-images.githubusercontent.com/3220162/33506570-45b7148e-d6a5-11e7-8b09-853979bad6ce.png)

What WooCommerce Services does is combines the GST and PST into one tax:
![screen shot 2017-12-01 at 14 39 26](https://user-images.githubusercontent.com/3220162/33506614-8ad51840-d6a5-11e7-93e3-f1788877932b.png)
Which means you're then unable to separate them and only charge one of them on Shipping.

What the TaxJar API should be doing is adding 2 tax rates to each Province, with the correct GST and PST for each, and then only checking off the "Shipping" box for the GST section.

The workaround, for now, is to ask users to disable Automatic Taxes and have them enter in their taxes for Canada manually.

**Comment by fastdivision** [comment]
Unfortunately this is a complex issue that will likely take awhile to implement on our end. We'll need to update our API to correctly determine how to handle freight taxability for this scenario and refactor the TaxJar plugin to create multiple tax rates for GST / PST in Canada. I brought it up with our team and our sales tax analyst will write up the requirements soon.

**Comment by RaviTimUI** [comment]
@jeffstieler 
Can you please explain the steps of the workaround you did on the canada tax issue?

**Comment by dallendalton** [comment]
I am closing this issue due to its age and inactivity. We do not currently have plans to implement this change. If this is still an issue or you have additional comments please feel free to add them and we will revisit it.

**Comment by TBeblar** [comment]
This is 100% still an issue and should not be dismissed so easily. In BC Canada the tax rate is 5% + 7% which is different than 12% since the taxes are applied individually and rounded at each step. Accounting software (like QuickBooks) does this correctly. Applying a 12% tax when it should be 5% + 7% leads to penny rounding issues. We use TaxJar to calc taxes in the USA but for Canada, TaxJar simply does not work. I was forced to implement a custom solution for Canada and ignore TaxJar in the country. Please reopen this ticket.
