### ISSUE TITLE
Automatic tax class setup from /v2/categories?

### ISSUE THREAD

**Issue by jeffstieler** [taxjar/taxjar-woocommerce-plugin#65]
I was hoping to get to this during a "hack week", but didn't end up having time - so I'm sharing the idea with y'all. 🙂 

> TaxJar supports certain product categories and tax exemptions. Their documentation for setup is here: https://support.taxjar.com/article/309-overriding-tax-rates-and-exempting-products-in-woocommerce
> 
> Using the /v2/categories endpoint, we can retrieve a list of supported tax categories and create tax classes based on them as a convenience for our users.

_From: https://github.com/Automattic/woocommerce-services/issues/1306_

**Comment by dallendalton** [comment]
I am closing this issue due to its age to help clean up the repository. We have recorded this feature request though it is not currently on the roadmap. Thanks again for submitting this suggestion.
