### ISSUE TITLE
Taxes are being calculated for Zero rate rates

### ISSUE THREAD

**Issue by bpurdyiv** [taxjar/taxjar-woocommerce-plugin#71]
I am running into an issue where tax rates are being calculated for the 'Zero rate rates'
I would assume that Zero rates, were just that, 0% ?

I have certain customers set to have the Zero rate rates, and would like to be able to not have these automatically calculated, or maybe setup an additional tax class that isn't automatically calculated?

**Comment by fastdivision** [comment]
@bpurdyiv For products assigned to a "Zero Rate" tax class or set to "None" tax status, we should exempt those products from sales tax: https://github.com/taxjar/taxjar-woocommerce-plugin/blob/f41f124065806a5273184d28e16aaf37213d5ab3/includes/class-wc-taxjar-integration.php#L640

Additionally, we check if a customer is VAT exempt here to completely exempt them from tax: https://github.com/taxjar/taxjar-woocommerce-plugin/blob/f41f124065806a5273184d28e16aaf37213d5ab3/includes/class-wc-taxjar-integration.php#L337

Are you using a specific plugin to assign certain customers to Zero rate rates? Can you list out the steps to reproduce this issue so I can test locally on my end? Thank you!

**Comment by bpurdyiv** [comment]
@fastdivision Thanks for the response. Issue was completely my fault. I had `'zero rate'` instead of `'zero-rate'`. I was up to late...
