### ISSUE TITLE
Conflict with WooCommerce Smart Coupons

### ISSUE THREAD

**Issue by imfromio** [taxjar/taxjar-woocommerce-plugin#86]
I am using WooCommerce Smart Coupons to provide store credit to customers. When TaxJar is activated and a customer uses a store credit, the credit balance will be set to $0.00 after checkout even if there should be a remaining balance.

I have switched to a default 2017 theme and disabled all plugins except WooCommerce, TaxJar, and Smart Coupons. The error persists. If I deactivate TaxJar and place an order with a store credit, the credit balance will be correct. 

You can test this by adding this product to an empty cart, then use a store credit with a value higher than the cart total. The cart, checkout, and confirmation totals all look correct. Aftre checkout, the store credit should have a balance remaining, but if you try repeating the order and using the same store credit, you will see that the credit has $0.00 balance. In the backend, the credit also shows a $0.00 balance.

Our site relies heavily on the use of store credit, so we would like to have this resolved quickly. Can you take a look at this issue?

**Comment by fastdivision** [comment]
Hi @imfromio, thank you for your patience while we investigated this issue between TaxJar and WC Smart Coupons. We're currently testing a fix via #98 and it should be available in our next update.

**Comment by imfromio** [comment]
Hi @fastdivision, thanks for your response. I can confirm that the fix via #98 is working for my configuartion: WP 5.0.3, WC 3.5.5, Smart Coupons 4.0.0 and TaxJar 2.0.1.

Any ETA on when the new update will be released?

**Comment by IsaacMiller** [comment]
Any news on when this will be released? I've been putting of deploying the code change manually but I may need to just that if it's going to take much longer.

**Comment by dallendalton** [comment]
@IsaacMiller - This will be included in our next release which should be available late this week or early next week. Thanks!

**Comment by fastdivision** [comment]
Merged #98, releasing this week.
