### ISSUE TITLE
Make this plugin work in the EU

### ISSUE THREAD

**Issue by enoch85** [taxjar/taxjar-woocommerce-plugin#91]
Hi!

Your plugin for Woocommerce does the tax calculations wrong if you are a EU based shop selling to other EU countries.

All the taxes it calculates is 25% (Swedish tax, I'm based in Sweden) even if the customer is based in let's say Germany (where the tax is 19%)

When looking in the log it seems like it's basing the tax on the shop origin ("tax_source":"origin") rather than the buyers origin which is wrong.

Please correct, or advice. Been trying to get automated taxes in Woocommerce to work for like 1 week now.

I'm based in EU and only interested in rates for member EU states to apply to EU law,

Thanks!

**Answer from your support:**

Thank you for reaching out, I'm happy to help with this!

*What's happening is our API calculates the VAT rate of the origin rather than the destination* because that's how needs to be calculated for people selling under a certain threshold. Most of our customers are small businesses and won't cross the threshold, so that's why we have it this way. We have more details on that in our blog post here.

Out of the box, we do not yet have a way to flip this in WooCommerce. I apologize for this inconvenience.

If you'd like, and if you have developer resources - because our WooCommerce plugin is open source, you can fix this by swapping the "to" and "from" parameters in the calls to our API. That way you will be charging destination rates instead of origin rates. This would be in this method:
https://github.com/taxjar/taxjar-woocommerce-plugin/blob/2.0.1/includes/class-wc-taxjar-integration.php#L275

I hope that helps, please let me know if you have further questions!

**Comment by enoch85** [comment]
Suggestion, make it an option to set the maximum threshold. Or make it available to change `to` to `from` in your API.

**Comment by enoch85** [comment]
**From support:**

I do appreciate you taking the time to share your feedback and will make sure that this is brought up with my team. However, as I mentioned previously there are thresholds in place where a seller does not need to collect at destination and can collect origin based rates, see our blog post here: https://blog.taxjar.com/european-vat-us-ecommerce-sellers/. At this time this is the best option for most of our users because they are mostly under these thresholds, and we don't have plans to change it. Though you could change it if that's what you need as I described previously.


Thank you, have a nice day

**From me:**

Hi Tiffany,


Well, I'm not a lawyer, but in Sweden (and the rest of EU I believe) there is something called MOSS. This is from the Swedish tax agency: https://translate.google.com/translate?sl=sv&tl=en&u=https%3A%2F%2Fwww.skatteverket.se%2Fforetagochorganisationer%2Fmoms%2Fdeklareraochbetalamoms%2Fmossredovisningavmomspaelektroniskatjanster.4.3aa8c78a1466c5845876a05.html


*When you sell certain digital services, you must charge VAT according to the rules applicable in the country where the buyer is located.*


So I don't think your information is correct. I understand it's difficult to comply to all EU laws if you are an USA based company, but please update your informaition accordingly.


Thank you!

**Comment by dallendalton** [comment]
I am closing this issue due to its age to help clean up the repository. A lot has changed since this issue was submitted and this issue may no longer reflect the current state of TaxJar or the TaxJar WooCommerce plugin. Thanks for submitting this issue! Feel free to comment here or open a new issue if you still feel this needs resolution.
