### ISSUE TITLE
Undefined Index error?

### ISSUE THREAD

**Issue by Grynn07** [taxjar/taxjar-woocommerce-plugin#94]
I get the following error: 

Notice: Undefined index: enabled in /wp-content/plugins/taxjar-simplified-taxes-for-woocommerce/includes/class-wc-taxjar-integration.php on line 42

Any tips on what is going on here? I read that I need to add "isset" somewhere on that line, but I'm not much of a programmer.

**Comment by fastdivision** [comment]
Hi @Grynn07, is this error preventing you from using the TaxJar plugin? Yes it might be as simple as using `isset` prior to checking the value on line 42:

```php
if ( isset( $this->settings['enabled'] ) && 'yes' == $this->settings['enabled'] ) {
```

Let me know if this resolves the issue. Thank you!

**Comment by Grynn07** [comment]
That did it, thank you!! 

Will this updated code be added to the next TaxJar update?
